{- Paths_* file is normally auto generated by cabal.

    This file is only required for development (to provide version),
    for example with 'ghcid':

    $ nix-shell
    $ ghcid "--command=ghci -Wall -iother -ilib -iapp app/Main.hs
-}

module Paths_aspecs where

import Data.Version

-- | Empty version, for development mode.
version :: Data.Version.Version
version = Data.Version.Version [] []

