file_name := "cat150/cat-3.0.ast"

validate:
    aspecs validate -f {{file_name}} --ast --warnings

prettify:
    aspecs prettify --remove-comments {{file_name}} --ast

build:
    ./build_spec.sh {{file_name}}