{- Paths_* file is normally auto generated by cabal.
   This is only required to provode 'version' for development environment.
-}

module Paths_aspecs where

import           Data.Version

-- | Empty version, for development mode.
version :: Data.Version.Version
version = Data.Version.Version [] []

